### ISSUE TITLE
Problem running egcurl

### ISSUE THREAD

**Issue by mobijay** [akamai/edgegrid-curl#25]
I'm asked to install edgegrid-python even though it is already installed.

1. Cloned the edgegrid-curl project
2. Created the .edgerc file in the home directory
3. I installed edgegrid-python
4. I then ran egcurl
This tool has been updated to use the Akamai EdgeGrid for Python library
to sign requests. That library will need to be installed before you can
make a request.

Please run this command to install the required library:

pip install edgegrid-python

~/Projects/gitrepos/edgegrid-curl$ pip install edgegrid-python
Requirement already satisfied: edgegrid-python in /Library/Python/2.7/site-packages (1.1.0)
Requirement already satisfied: requests>=2.3.0pyopenssl in /Users/jmobijoh/Library/Python/2.7/lib/python/site-packages (from edgegrid-python) (2.18.1)
Requirement already satisfied: ndg-httpsclient in /Library/Python/2.7/site-packages (from edgegrid-python) (0.4.4)
Requirement already satisfied: pyasn1 in /Library/Python/2.7/site-packages (from edgegrid-python) (0.4.2)
Requirement already satisfied: urllib3 in /Users/jmobijoh/Library/Python/2.7/lib/python/site-packages (from edgegrid-python) (1.21.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jmobijoh/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0pyopenssl->edgegrid-python) (2017.4.17)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/jmobijoh/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0pyopenssl->edgegrid-python) (3.0.4)
Requirement already satisfied: idna<2.6,>=2.5 in /Users/jmobijoh/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0pyopenssl->edgegrid-python) (2.5)
Requirement already satisfied: PyOpenSSL in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from ndg-httpsclient->edgegrid-python) (0.13.1)

**Comment by elreydetodo** [comment]
@mobijay I have had some reports of this issue in the past, but have been unable to reproduce it myself. It seems to be something about the base Python version included with OSX, but I can't quire figure out what the issue is. My OSX version of python is broken and I've been using a version from Homebrew for a long time.

Can you try upgrading pyopenssl and see if that works? I think the issue may be that the minimum version in edgegrid-python is incorrect but I can't test it myself because of my broken python environment. You can upgrade with `pip install -U pyopenssl`. Note that you probably won't be able to run this with sudo, it's somehow protected by the OS. That's part of how I broke my local python library...

**Comment by mobijay** [comment]
I'm on python 2.7.10. Do you have the latest version of python?

**Comment by elreydetodo** [comment]
I'm also running 2.7.10, but I don't have the same issue locally. I think it's because I have manually upgrade some dependency to newer than whatever was required by edgegrid-python. I suspect the minimum version of pyopenssl is incorrect, which is why I suggested upgrading it.

**Comment by mobijay** [comment]
Thank you for your help. Your suggestion worked and I am able to make calls!

**Comment by elreydetodo** [comment]
I've notified the maintainer of edgegrid-python and I'll try to work with her to get the minimum version for pyopenssl fixed there.
