### ISSUE TITLE
egcurl crashes on python3 when it calls python2 `config.itervalues()`

### ISSUE THREAD

**Issue by vitaly-krugl** [akamai/edgegrid-curl#27]
```
Traceback (most recent call last):
  File "/Users/vkruglik/ace/egcurl", line 333, in <module>
    sys.exit(main())
  File "/Users/vkruglik/ace/egcurl", line 254, in main
    config = get_config(args.eg_edgerc, args.eg_config, section)
  File "/Users/vkruglik/ace/egcurl", line 79, in get_config
    configs = _parse_egcurl(egconf_filename)
  File "/Users/vkruglik/ace/egcurl", line 133, in _parse_egcurl
    if None in config.itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'
```

To fix, this line should be just the following for python2 & python3 compatibility:
```
if None in config.values()
```

**Comment by elreydetodo** [comment]
I've fixed this issue. The fact that you encountered the issue at all means you're likely using a very old format `.egcurl` config file. You should consider upgrading it to an edgerc file (basically an ini file format) because it's more compatible with other Akamai OPEN signing tools. There's a tool in the repo to help with that. You can run this command to convert your `~/.egcurl` into an `~/.edgerc`:
```
./convert_egcurl.pl < ~/.egcurl > ~/.edgerc
```

I'm also curious how your credential remains active given that we haven't produced this format from Akamai Control Center for several years, and credentials typically expire on a much more regular interval than that. Surely ACC provided you a credential in the newer edgerc format any number of times that you've renewed it in the past two years..?

Regardless of the age of your credential, note that I added a warning in the code if the credential specifies a "max-body" value of 8192. The API credential tool used to provide that value in its default credentials, but it was incorrect. I thought if you were using a very old credential you might have acquired it from back in the time when the tools mistakenly did that. If so, signing POST requests over 8192B will likely fail. Adding the warning seemed sensible.

**Comment by vitaly-krugl** [comment]
@elreydetodo Thanks for following up. I replied via internal email.
